export const PLANS = [
  {
    key: 'starter',
    name: 'Starter',
    price: 0,
    priceLabel: 'Free',
    priceSub: 'forever',
    description: 'Perfect for testing the water. Get a feel for the tool before committing.',
    badge: null,
    highlight: false,
    cta: 'Get Started Free',
    features: [
      { text: '5 website audits per month', included: true },
      { text: '3 lead searches per month', included: true },
      { text: 'AI audit report', included: true },
      { text: 'Basic outreach kit (email only)', included: true },
      { text: 'Audit history (last 10)', included: true },
      { text: 'PDF & Excel export', included: false },
      { text: 'All 4 outreach formats', included: false },
      { text: 'Call list & pipeline CRM', included: false },
      { text: 'White-label PDF reports', included: false },
      { text: 'Team seats', included: false },
    ],
  },
  {
    key: 'pro',
    name: 'Pro',
    price: 49,
    priceLabel: '$49',
    priceSub: 'per month',
    description: 'Everything you need to find, pitch, and win web clients consistently.',
    badge: 'Most Popular',
    highlight: true,
    cta: 'Start Pro — $49/mo',
    features: [
      { text: 'Unlimited website audits', included: true },
      { text: 'Unlimited lead searches', included: true },
      { text: 'AI audit report', included: true },
      { text: 'All 4 outreach formats', included: true },
      { text: 'Full audit history', included: true },
      { text: 'PDF & Excel export', included: true },
      { text: 'Call list & pipeline CRM', included: true },
      { text: 'Priority support', included: true },
      { text: 'White-label PDF reports', included: false },
      { text: 'Team seats', included: false },
    ],
  },
  {
    key: 'agency',
    name: 'Agency',
    price: 149,
    priceLabel: '$149',
    priceSub: 'per month',
    description: 'Built for agencies running audits at scale and delivering to clients.',
    badge: null,
    highlight: false,
    cta: 'Start Agency — $149/mo',
    features: [
      { text: 'Unlimited website audits', included: true },
      { text: 'Unlimited lead searches', included: true },
      { text: 'AI audit report', included: true },
      { text: 'All 4 outreach formats', included: true },
      { text: 'Full audit history', included: true },
      { text: 'PDF & Excel export', included: true },
      { text: 'Call list & pipeline CRM', included: true },
      { text: 'Priority support', included: true },
      { text: 'White-label PDF reports', included: true },
      { text: 'Team seats (up to 3)', included: true },
    ],
  },
] as const

export const FAQS = [
  {
    q: 'Can I cancel anytime?',
    a: 'Yes — no lock-in contracts. Cancel from your account settings and you keep access until the end of your billing period.',
  },
  {
    q: 'What counts as a website audit?',
    a: 'Each time you scan a URL through the audit tool, that counts as one audit. Reopening a saved audit from history does not count.',
  },
  {
    q: 'What counts as a lead search?',
    a: 'Each time you run a new search in the Lead Finder, that counts as one search. Reopening a past search from history is free.',
  },
  {
    q: 'Do I need a credit card to start?',
    a: 'No credit card required for the Starter plan. You only need payment details when upgrading to Pro or Agency.',
  },
  {
    q: 'What is white-label PDF?',
    a: 'Agency plan users can upload their own logo and remove sitesignal branding from exported PDF reports — so the report looks like it came from your studio.',
  },
  {
    q: 'Can I upgrade or downgrade later?',
    a: "Yes. You can upgrade instantly and downgrade at the end of your billing cycle. We'll prorate any mid-cycle upgrades.",
  },
  {
    q: 'Is this built for Australian web developers?',
    a: 'Yes — the lead finder is optimised for Australian businesses and locations. Pricing is in AUD.',
  },
]

export const COMPARISON_ROWS = [
  { feature: 'Website audits / month', starter: '5', pro: 'Unlimited', agency: 'Unlimited' },
  { feature: 'Lead searches / month', starter: '3', pro: 'Unlimited', agency: 'Unlimited' },
  { feature: 'AI audit report', starter: '✓', pro: '✓', agency: '✓' },
  { feature: 'Outreach formats', starter: 'Email only', pro: 'All 4', agency: 'All 4' },
  { feature: 'Audit history', starter: 'Last 10', pro: 'Full', agency: 'Full' },
  { feature: 'PDF export', starter: '✕', pro: '✓', agency: '✓' },
  { feature: 'Excel / CSV export', starter: '✕', pro: '✓', agency: '✓' },
  { feature: 'Call list & CRM', starter: '✕', pro: '✓', agency: '✓' },
  { feature: 'White-label PDF', starter: '✕', pro: '✕', agency: '✓' },
  { feature: 'Team seats', starter: '✕', pro: '✕', agency: 'Up to 3' },
  { feature: 'Priority support', starter: '✕', pro: '✓', agency: '✓' },
]
