// components/AuditReport.js
// ─────────────────────────────────────────────────────────
// Displays the full AI-generated report
// Also has a "Copy Report" button for easy use
// ─────────────────────────────────────────────────────────

'use client'
import { useState } from 'react'

export default function AuditReport({ report, url, scores }) {
  const [copied, setCopied] = useState(false)

  // Copy report to clipboard so you can paste it into an email
  const handleCopy = () => {
    const fullReport = `
WEBSITE AUDIT REPORT
Website: ${url}
Overall Score: ${scores.overallScore}/100
Scanned: ${new Date().toLocaleDateString('en-AU')}

${report}

─────────────────────────────
Report generated by Client Finder
    `.trim()
    
    navigator.clipboard.writeText(fullReport)
    setCopied(true)
    setTimeout(() => setCopied(false), 3000)
  }

  // Convert the markdown-style text from GPT into proper formatting
  // GPT uses **bold** and section headings we want to style nicely
  const formatReport = (text) => {
    return text
      .split('\n')
      .map((line, index) => {
        // Section headings (wrapped in **)
        if (line.startsWith('**') && line.endsWith('**')) {
          return (
            <h3 key={index} className="text-lg font-bold text-gray-800 mt-6 mb-2 border-b border-gray-200 pb-1">
              {line.replace(/\*\*/g, '')}
            </h3>
          )
        }
        // Bullet points
        if (line.startsWith('- ')) {
          return (
            <li key={index} className="text-gray-700 ml-4 mb-1 list-disc">
              {line.substring(2)}
            </li>
          )
        }
        // Empty lines = spacing
        if (line.trim() === '') {
          return <br key={index} />
        }
        // Normal paragraphs
        return (
          <p key={index} className="text-gray-700 mb-2 leading-relaxed">
            {line}
          </p>
        )
      })
  }

  return (
    <div className="bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden">
      
      {/* Report Header */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-800 p-6 text-white">
        <div className="flex justify-between items-start">
          <div>
            <h2 className="text-2xl font-bold">Website Audit Report</h2>
            <p className="text-blue-200 text-sm mt-1 break-all">{url}</p>
            <p className="text-blue-200 text-xs mt-1">
              {new Date().toLocaleDateString('en-AU', { 
                weekday: 'long', 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}
            </p>
          </div>
          
          {/* Big overall score */}
          <div className="text-center bg-white bg-opacity-20 rounded-xl p-4 min-w-[80px]">
            <div className="text-4xl font-bold">{scores.overallScore}</div>
            <div className="text-xs text-blue-200">out of 100</div>
          </div>
        </div>
      </div>

      {/* Quick Stats Bar */}
      <div className="grid grid-cols-4 divide-x divide-gray-200 border-b border-gray-200">
        {[
          { label: 'Performance', value: scores.mobile.performance },
          { label: 'SEO', value: scores.mobile.seo },
          { label: 'Accessibility', value: scores.mobile.accessibility },
          { label: 'Best Practices', value: scores.mobile.bestPractices },
        ].map((item) => (
          <div key={item.label} className="p-3 text-center">
            <div className={`text-xl font-bold ${
              item.value >= 70 ? 'text-green-600' :
              item.value >= 50 ? 'text-yellow-600' : 'text-red-600'
            }`}>
              {item.value}
            </div>
            <div className="text-xs text-gray-500">{item.label}</div>
          </div>
        ))}
      </div>

      {/* Technical Details Row */}
      <div className="grid grid-cols-3 gap-2 p-4 bg-gray-50 border-b border-gray-200">
        <div className="text-center">
          <div className="text-xs text-gray-500">Load Time</div>
          <div className="font-semibold text-sm">{scores.details.loadTime}</div>
        </div>
        <div className="text-center">
          <div className="text-xs text-gray-500">SSL / HTTPS</div>
          <div className="font-semibold text-sm">
            {scores.details.isHttps ? '✅ Yes' : '❌ No'}
          </div>
        </div>
        <div className="text-center">
          <div className="text-xs text-gray-500">Meta Description</div>
          <div className="font-semibold text-sm">
            {scores.details.hasMetaDescription ? '✅ Yes' : '❌ Missing'}
          </div>
        </div>
      </div>

      {/* AI Report Content */}
      <div className="p-6">
        <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
          🤖 AI Analysis
        </h2>
        <div className="prose max-w-none">
          {formatReport(report)}
        </div>
      </div>

      {/* Contact Footer - THIS IS YOUR CTA */}
      <div className="bg-gradient-to-r from-gray-800 to-gray-900 p-6 text-white">
        <p className="text-gray-400 text-sm mb-2">Report prepared by</p>
        <h3 className="text-xl font-bold">Your Name Here</h3>
        <p className="text-gray-300 text-sm">Web Developer & Designer</p>
        <div className="flex flex-wrap gap-4 mt-3 text-sm">
          <span>📞 0400 000 000</span>
          <span>📧 you@email.com.au</span>
          <span>🌐 yourwebsite.com.au</span>
        </div>
        <p className="text-blue-400 text-sm mt-3 font-medium">
          💬 All issues found above can be fixed. Book a free 15-minute call to find out how.
        </p>
      </div>

      {/* Action Buttons */}
      <div className="p-4 bg-gray-50 flex gap-3 flex-wrap">
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors"
        >
          {copied ? '✅ Copied!' : '📋 Copy Report'}
        </button>
        <button
          onClick={() => window.print()}
          className="flex items-center gap-2 bg-gray-600 hover:bg-gray-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors"
        >
          🖨️ Print / Save PDF
        </button>
      </div>
    </div>
  )
}